# Maintenance Mode
MAINTENANCE: # bungeecord.command.maintenance
  ENABLED: false
  HUB-NAME: "Hub-01"
  PING-TEXT: "&4Whitelisted" # Player Slots Text
  KICK-MESSAGE:
    - ""
    - "&cThe network is currently in maintenance."
    - "&cAdditional info may be found at our discord!"
    - ""
  PLAYERS: []
  
# Kick System
KICK:
  MESSAGE: "&cKicked from &f"

# Social Media
TEAMSPEAK:
  MESSAGE:
    - "&7&m-----------------------------"
    - "&dTeamspeak&7: &f&ots.spacehcf.us"
    - "&7&m-----------------------------"
STORE:
  MESSAGE:
    - "&7&m-----------------------------"
    - "&dStore&7: &f&ostore.spacehcf.us"
    - "&7&m-----------------------------"
DISCORD:
  MESSAGE:
    - "&7&m-----------------------------"
    - "&dDiscord&7: &f&odiscord.spacehcf.us"
    - "&7&m-----------------------------"
TWITTER:
  MESSAGE:
    - "&7&m-----------------------------"
    - "&dTwitter&7: &f&o@SpaceHCFUS"
    - "&7&m-----------------------------"
WEBSITE:
  MESSAGE:
    - "&7&m-----------------------------"
    - "&dWebsite&7: &f&owww.spacehcf.us"
    - "&7&m-----------------------------"

# Help Command
HELP:
  MESSAGE:
    - "&7&m----------------------------------------"
    - "&d&lSpaceHCF Network &7(%bungee_total%/3,500)"
    - ""
    - "&3■ &dTeamspeak&7: &f&ots.spacehcf.us"
    - "&b■ &dTwitter&7: &f&ots.spacehcf.us"
    - "&a■ &dStore&7: &f&ots.spacehcf.us"
    - "&2■ &dWebsite&7: &f&owww.spacehcf.us"
    - "&9■ &dDiscord&7: &f&odiscord.spacehcf.us"
    - ""
    - "&4⚠ &cFor instant assistance join our teamspeak!"
    - "&7&m----------------------------------------"

# Misc Utils Commands
FIND:
  MESSAGE: "&fis currently on"
  FINAL: "&f." # Final Message: &d<player> &fis currently on &d<server>&f.
  PLAYER_COLOR: "&d" # Only works in main message.
  SERVER_COLOR: "&d" # Only works in main message.
  OFFLINE: "&cis currently not on the network."
  OFFLINE_PLAYER_COLOR: "&c" # Only works in offline message.
  USAGE: "&cUsage: /find <player>"
HUB:
  MESSAGE: "&dSending you to the &f"
  FINAL: "&d..." # Final Message: &dSending you to the &fHub-01&d...
  HUB-NAME: "Hub-01"
SERVER:
  MESSAGE: "&dConnecting you to &f"
  FINAL: "&d!" # Final Message: &dConnecting you to &f<server>&d!
  CONNECTED: "&dYou are currently connected to &f"
  CONNECTED_FINAL: "&d." # Final Message: &dYou are currently connected to &f<server>&d.
  USAGE: "&dConnect to a server with &f/server <name>&d."
  SERVERS: "&dServers&7: &f"
  FORMAT: "&7, &f" # Ex: &dServers&7: &fLobby&7, &fHCF
  NO_PERMISSION: "&cYou don't have permissions." # bungeecord.command.server
  